
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: symfony
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  fluentbit:
    image: fluent/fluent-bit:4.0.13
    environment:
      LOKI_URL: 104.155.107.5
      LOKI_PORT : 3100
      LOG_NAME: sender=crud_app
    container_name : fluentbit
    restart : unless-stopped
    volumes:
      - ./app/var/logs/crud:/var/log/symfony:ro
      - ./app/fluentbit:/var/log/fluentbit
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
